name: Deploy to Hostinger VPS with OAuth Cleanup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Hostinger VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          echo "🚀 Starting deployment to Hostinger VPS..."
          
          # Navigate to project directory
          cd /home/${{ secrets.HOSTINGER_USERNAME }}/jobportal
          
          # Pull latest changes
          echo "📥 Pulling latest changes..."
          git pull origin main
          
          # Install dependencies
          echo "📦 Installing dependencies..."
          npm install
          
          # Build the application
          echo "🔨 Building application..."
          npm run build
          
          # Clean OAuth users from database
          echo "🗑️ Cleaning OAuth users from database..."
          node scripts/clear-oauth-users-simple.js
          
          # Restart the application
          echo "🔄 Restarting application..."
          pm2 restart jobportal
          
          # Check application status
          echo "✅ Checking application status..."
          pm2 status
          
          echo "🎉 Deployment completed successfully!"
        port: 22
        sync: false
        use_insecure_cipher: false
        timeout: 30s
        command_timeout: 15m
        proxy_port: 22
        proxy_timeout: 30s
        proxy_use_insecure_cipher: false
        script_stop: false
        debug: true
