# Simple Docker setup for development
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: jobportal-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jobportal
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build: .
    container_name: jobportal-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/jobportal?authSource=admin
      - NEXTAUTH_SECRET=your-production-secret-here
      - PORT=8000
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data: