version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=test-secret-key
    depends_on:
      - backend
    volumes:
      - ./uploads:/app/uploads

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://localhost:27017
      - JWT_SECRET_KEY=test-jwt-secret
    volumes:
      - ./uploads:/app/uploads

  # Optional: Add MongoDB for local testing
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_DATABASE=naukrimili
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data: