services:
  - type: web
    name: jobportal-next
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
    autoDeploy: true
    branch: main
    healthCheckPath: /api/health
    domains:
      - jobportal.example.com
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
