#!/bin/bash
# Resume Upload & Job Recommendations - Server Testing Commands
# Run each command one at a time and verify the response

echo "=================================================="
echo "Resume Upload & Job Recommendations Testing"
echo "=================================================="
echo ""
echo "🔧 FIXES APPLIED:"
echo "  ✅ Added 10MB file size limit with validation"
echo "  ✅ Fixed authentication handling"
echo "  ✅ Integrated job recommendations with upload"
echo "  ✅ Added recommendations display in frontend"
echo "  ✅ Enhanced error messages"
echo ""
echo "=================================================="
echo "COMMAND 1: Check Server Health"
echo "=================================================="
echo "Run this command:"
echo ""
echo "curl -X GET \"http://localhost:3000/api/health\" -H \"Content-Type: application/json\""
echo ""
echo "Expected: {\"success\":true,\"status\":\"ok\"}"
echo ""
echo "Press Enter when ready for next command..."
read

echo ""
echo "=================================================="
echo "COMMAND 2: Test Job Recommendations API (No Auth)"
echo "=================================================="
echo "Run this command:"
echo ""
echo "curl -X GET \"http://localhost:3000/api/jobseeker/recommendations-test?limit=3&algorithm=skills\" -H \"Content-Type: application/json\""
echo ""
echo "Expected: JSON with job recommendations and match scores"
echo ""
echo "Press Enter when ready for next command..."
read

echo ""
echo "=================================================="
echo "COMMAND 3: Check Auth Status"
echo "=================================================="
echo "Run this command:"
echo ""
echo "curl -X GET \"http://localhost:3000/api/debug/auth-status\" -H \"Content-Type: application/json\""
echo ""
echo "Expected: Auth status info (will show no user if not logged in)"
echo ""
echo "Press Enter when ready for next command..."
read

echo ""
echo "=================================================="
echo "COMMAND 4: Test Stats API"
echo "=================================================="
echo "Run this command:"
echo ""
echo "curl -X GET \"http://localhost:3000/api/stats\" -H \"Content-Type: application/json\""
echo ""
echo "Expected: Dashboard statistics"
echo ""
echo "Press Enter when ready for next command..."
read

echo ""
echo "=================================================="
echo "COMMAND 5: Get Recent Jobs"
echo "=================================================="
echo "Run this command:"
echo ""
echo "curl -X GET \"http://localhost:3000/api/jobs?limit=3&page=1\" -H \"Content-Type: application/json\""
echo ""
echo "Expected: List of 3 recent jobs"
echo ""
echo "Press Enter when ready for frontend test..."
read

echo ""
echo "=================================================="
echo "FRONTEND TESTING (Manual)"
echo "=================================================="
echo ""
echo "Now test the complete flow in the browser:"
echo ""
echo "1. Open: http://localhost:3000/auth/signin"
echo "2. Log in with Google or credentials"
echo "3. Navigate to: http://localhost:3000/resumes/upload"
echo "4. Upload a resume file (PDF, DOC, DOCX, or TXT)"
echo "5. Click 'Upload & Analyze'"
echo "6. Verify:"
echo "   ✅ Profile form autofills with extracted data"
echo "   ✅ Skills appear as tags"
echo "   ✅ Experience and education sections populate"
echo "   ✅ Recommended Jobs section appears"
echo "   ✅ Shows 3 jobs with match scores"
echo "   ✅ Each job has match reasons"
echo "7. Edit any fields as needed"
echo "8. Click 'Save Profile'"
echo "9. Should redirect to dashboard with full recommendations"
echo ""
echo "Press Enter to see troubleshooting info..."
read

echo ""
echo "=================================================="
echo "TROUBLESHOOTING"
echo "=================================================="
echo ""
echo "❌ If you get '413 Request Entity Too Large':"
echo "   → File is larger than 10MB. Use a smaller file."
echo ""
echo "❌ If you get 'Authentication Required':"
echo "   → Make sure you're logged in first"
echo "   → Try logging out and back in"
echo "   → Check browser console for session errors"
echo ""
echo "❌ If no recommendations show:"
echo "   → Check if resume has skills"
echo "   → Verify there are active jobs in database"
echo "   → Check browser console for errors"
echo ""
echo "❌ If form doesn't autofill:"
echo "   → Check browser console logs"
echo "   → Verify API response includes profile data"
echo "   → Try uploading a different resume"
echo ""
echo "=================================================="
echo "NEXT STEPS"
echo "=================================================="
echo ""
echo "✅ All server-side fixes are deployed"
echo "✅ Frontend is updated with recommendations display"
echo "✅ File size limit increased to 10MB"
echo "✅ Better error handling and messages"
echo ""
echo "🎯 To commit these changes:"
echo "   git add ."
echo "   git commit -m \"Fix resume upload with job recommendations\""
echo "   git push origin main"
echo ""
echo "📊 Monitor logs in production:"
echo "   pm2 logs naukrimili"
echo ""
echo "=================================================="
echo "Testing Complete!"
echo "=================================================="

