/** Retired templates map to an active premium template for saved resumes / exports. */
const RETIRED_TEMPLATE_ALIASES: Record<string, string> = {
  'ivory-boardroom-executive': 'luxe-executive',
  'royal-copper-executive': 'luxe-executive',
  'fashion-editorial-premium': 'elegant-ivory',
  'rosewood-modern': 'luxe-executive',
  'cascade-flow': 'soft-coral-executive',
  'lumen-studio': 'elegant-ivory',
  'executive-mosaic': 'luxe-executive',
  'executive-timeline': 'luxe-executive',
  'nordic-fusion': 'elegant-ivory',
  'modern-edge': 'luxe-executive',
  'prism-edition': 'elegant-ivory',
  'executive-slate': 'luxe-executive',
  'verdant-scandi-executive': 'elegant-ivory',
  'executive-copper': 'luxe-executive',
  'platinum-executive-edge': 'luxe-executive',
  'editorial-mauve': 'elegant-ivory',
  'executive-corporate': 'luxe-executive',
  'executive-modern': 'luxe-executive',
  'charcoal-premium': 'luxe-executive',
  'executive-minimal-pro': 'luxe-executive',
  'royal-edge': 'luxe-executive',
  'velvet-ribbon-executive': 'elegant-ivory',
  'aether-professional': 'elegant-ivory',
  'nordic-creative-executive': 'elegant-ivory',
  'executive-burgundy-diamond': 'luxe-executive',
  'maroon-gold-executive': 'luxe-executive',
  'executive-sidebar-elite': 'luxe-executive',
  'horizon-canvas': 'elegant-ivory',
  'soft-sage-professional': 'elegant-ivory',
  'executive-graphite': 'luxe-executive',
  'luxury-corporate': 'luxe-executive',
  'executive-navy-copper': 'luxe-executive',
  'organic-luxe-editorial': 'elegant-ivory',
  'executive-slate-luxe': 'luxe-executive',
  'slate-executive-pro': 'luxe-executive',
  'organic-luxe-executive': 'elegant-ivory',
  'velvet-horizon-executive': 'luxe-executive',
  'midnight-prestige-executive': 'luxe-executive',
  'frosted-glass-executive': 'elegant-ivory',
  'executive-redline-elite': 'luxe-executive',
  'aurora-executive-glass': 'elegant-ivory',
  'blush-executive-watercolor': 'elegant-ivory',
  'graphite-orange-executive': 'luxe-executive',
  'executive-coral-elite': 'luxe-executive',
};

export function resolveTemplateId(templateId: string): string {
  return RETIRED_TEMPLATE_ALIASES[templateId] ?? templateId;
}
