name: jobportal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - opencv>=4.8.0
  - pillow>=10.2.0
  - pip>=23.2.1
  - pip:
    - flask==3.0.2
    - flask-cors==4.0.0
    - flask-jwt-extended==4.6.0
    - flask-restful>=0.3.10
    - pymongo==4.6.2
    - python-dotenv==1.0.1
    - bson==0.5.10
    - PyPDF2>=3.0.0
    - python-docx>=0.8.11
    - PyMuPDF>=1.22.3
    - pytesseract>=0.3.10
    - imagehash>=4.3.1
    - python-magic>=0.4.27
    - python-magic-bin>=0.4.14
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - mypy>=1.4.0
    - types-Pillow>=10.0.0
    - types-PyPDF2>=3.0.0
    - black>=23.7.0
    - flake8>=6.0.0
    - isort>=5.12.0
