// Sample Indian jobs for demo purposes
export const sampleIndianJobs = [
  {
    id: '1',
    title: 'Software Engineer',
    company: { display_name: 'Tata Consultancy Services' },
    location: { display_name: 'Mumbai, Maharashtra' },
    salary_min: 600000,
    salary_max: 1200000,
    description: 'Develop and maintain web applications using modern frameworks. Collaborate with cross-functional teams.',
    redirect_url: 'https://www.tcs.com/careers',
    created: new Date().toISOString(),
    isUrgent: true,
    isRemote: false,
    contract_type: 'Full-time',
  },
  {
    id: '2',
    title: 'Data Analyst',
    company: { display_name: 'Infosys' },
    location: { display_name: 'Bangalore, Karnataka' },
    salary_min: 500000,
    salary_max: 1000000,
    description: 'Analyze data trends and provide actionable insights. Proficiency in SQL and Python required.',
    redirect_url: 'https://www.infosys.com/careers',
    created: new Date().toISOString(),
    isUrgent: false,
    isRemote: true,
    contract_type: 'Full-time',
  },
  {
    id: '3',
    title: 'Marketing Manager',
    company: { display_name: 'Reliance Industries' },
    location: { display_name: 'Delhi' },
    salary_min: 800000,
    salary_max: 1500000,
    description: 'Lead marketing campaigns and manage a team of executives. Experience in FMCG preferred.',
    redirect_url: 'https://www.ril.com/careers',
    created: new Date().toISOString(),
    isUrgent: false,
    isRemote: false,
    contract_type: 'Full-time',
  },
  {
    id: '4',
    title: 'HR Executive',
    company: { display_name: 'Wipro' },
    location: { display_name: 'Hyderabad, Telangana' },
    salary_min: 400000,
    salary_max: 800000,
    description: 'Manage recruitment and employee engagement activities. Good communication skills required.',
    redirect_url: 'https://careers.wipro.com',
    created: new Date().toISOString(),
    isUrgent: false,
    isRemote: false,
    contract_type: 'Full-time',
  },
  {
    id: '5',
    title: 'Teacher',
    company: { display_name: 'Delhi Public School' },
    location: { display_name: 'Delhi' },
    salary_min: 300000,
    salary_max: 600000,
    description: 'Teach mathematics to high school students. B.Ed. mandatory.',
    redirect_url: 'https://dpsdelhi.org/careers',
    created: new Date().toISOString(),
    isUrgent: false,
    isRemote: false,
    contract_type: 'Full-time',
  },
  {
    id: '6',
    title: 'Nurse',
    company: { display_name: 'Apollo Hospitals' },
    location: { display_name: 'Chennai, Tamil Nadu' },
    salary_min: 350000,
    salary_max: 700000,
    description: 'Provide patient care and assist doctors in procedures. Nursing degree required.',
    redirect_url: 'https://www.apollohospitals.com/careers',
    created: new Date().toISOString(),
    isUrgent: true,
    isRemote: false,
    contract_type: 'Full-time',
  },
]; 