name: 🚀 Production Deployment (Webhook)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: |
        echo "📦 Installing dependencies with Node $(node --version)..."
        npm install --legacy-peer-deps --engine-strict=false --force
        
    - name: 🔨 Build application
      run: |
        echo "🔨 Building application with Node $(node --version)..."
        export NEXT_TELEMETRY_DISABLED=1
        export NODE_ENV=production
        npm run build
        
    - name: 🚀 Trigger Deployment Webhook
      run: |
        echo "🚀 Triggering deployment webhook..."
        curl -X POST http://aftionix.in:7777/webhook \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -d '{"ref":"refs/heads/main","repository":{"full_name":"Anamsayyed016/Naukrimili"}}'
        
        echo "✅ Deployment webhook triggered successfully!"
        
    - name: ⏳ Wait for Deployment
      run: |
        echo "⏳ Waiting for deployment to complete..."
        sleep 30
        
        # Test if deployment was successful
        echo "🔍 Testing deployment..."
        for i in {1..10}; do
          echo "Health check attempt $i/10..."
          if curl -f -s --max-time 10 http://aftionix.in/api/health > /dev/null 2>&1; then
            echo "✅ Deployment successful! Application is healthy."
            exit 0
          else
            echo "❌ Health check failed (attempt $i/10), waiting 15 seconds..."
            sleep 15
          fi
        done
        
        echo "⚠️ Deployment may still be in progress. Check server logs for details."
        exit 0
